--
-- PostgreSQL database dump
--

\restrict xEJwEGIQdkILJJ8gcuXaVfVZ2n9ToS57vYXqp9vdMEy5hGsHKbtnX0FUeOuAV3b

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auditoria_logs; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.auditoria_logs (
    id bigint NOT NULL,
    dados_anteriores text,
    dados_novos text,
    data_hora timestamp(6) without time zone NOT NULL,
    entidade character varying(100) NOT NULL,
    entidade_id bigint NOT NULL,
    observacao character varying(500),
    operacao character varying(255) NOT NULL,
    usuario_email character varying(255),
    usuario_id bigint,
    CONSTRAINT auditoria_logs_operacao_check CHECK (((operacao)::text = ANY ((ARRAY['CRIACAO'::character varying, 'ATUALIZACAO'::character varying, 'EXCLUSAO'::character varying, 'ATIVACAO'::character varying, 'INATIVACAO'::character varying, 'APROVACAO'::character varying, 'REPROVACAO'::character varying, 'AUTORIZACAO'::character varying])::text[])))
);


ALTER TABLE public.auditoria_logs OWNER TO technomade;

--
-- Name: auditoria_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.auditoria_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cartoes_credito; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.cartoes_credito (
    id bigint NOT NULL,
    bandeira character varying(255) NOT NULL,
    codigo_seguranca character varying(255) NOT NULL,
    nome_impresso character varying(255) NOT NULL,
    numero character varying(255) NOT NULL,
    preferencial boolean NOT NULL,
    cliente_id bigint
);


ALTER TABLE public.cartoes_credito OWNER TO technomade;

--
-- Name: cartoes_credito_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.cartoes_credito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cartoes_credito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorias; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.categorias (
    id bigint NOT NULL,
    nome character varying(255) NOT NULL
);


ALTER TABLE public.categorias OWNER TO technomade;

--
-- Name: categorias_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.categorias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.clientes (
    id bigint NOT NULL,
    cpf character varying(255),
    data_nascimento date,
    genero character varying(255),
    nome character varying(255),
    telefone character varying(255),
    usuario_id bigint NOT NULL,
    email character varying(255),
    CONSTRAINT clientes_genero_check CHECK (((genero)::text = ANY ((ARRAY['MASCULINO'::character varying, 'FEMININO'::character varying])::text[])))
);


ALTER TABLE public.clientes OWNER TO technomade;

--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compras; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.compras (
    id bigint NOT NULL,
    data_compra timestamp(6) without time zone NOT NULL,
    status_compra character varying(255) NOT NULL,
    valor_total double precision NOT NULL,
    endereco_entrega_id bigint NOT NULL,
    cliente_id bigint NOT NULL,
    frete double precision,
    data_entrega_prevista date,
    CONSTRAINT compras_status_compra_check CHECK (((status_compra)::text = ANY ((ARRAY['EM_PROCESSAMENTO'::character varying, 'APROVADA'::character varying, 'REPROVADA'::character varying, 'EM_TRANSITO'::character varying, 'ENTREGUE'::character varying, 'EM_TROCA'::character varying, 'TROCA_AUTORIZADA'::character varying, 'TROCA_RECUSADA'::character varying, 'TROCADA'::character varying])::text[])))
);


ALTER TABLE public.compras OWNER TO technomade;

--
-- Name: compras_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.compras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cupons; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.cupons (
    id bigint NOT NULL,
    codigo character varying(255) NOT NULL,
    promocional boolean NOT NULL,
    usado boolean NOT NULL,
    validade timestamp(6) without time zone,
    valor double precision NOT NULL,
    cliente_id bigint
);


ALTER TABLE public.cupons OWNER TO technomade;

--
-- Name: cupons_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.cupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enderecos_entrega; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.enderecos_entrega (
    id bigint NOT NULL,
    bairro character varying(255) NOT NULL,
    cep character varying(255) NOT NULL,
    cidade character varying(255) NOT NULL,
    estado character varying(255) NOT NULL,
    logradouro character varying(255) NOT NULL,
    nome_endereco character varying(255) NOT NULL,
    numero character varying(255) NOT NULL,
    observacoes character varying(255),
    pais character varying(255) NOT NULL,
    tipo_logradouro character varying(255) NOT NULL,
    tipo_residencia character varying(255) NOT NULL,
    cliente_id bigint,
    tipo_endereco character varying(255) DEFAULT 'ENTREGA'::character varying NOT NULL
);


ALTER TABLE public.enderecos_entrega OWNER TO technomade;

--
-- Name: enderecos_entrega_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.enderecos_entrega ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enderecos_entrega_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estoque; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.estoque (
    id bigint NOT NULL,
    fornecedor character varying(255) NOT NULL,
    quantidade integer NOT NULL,
    ultima_entrada timestamp(6) without time zone,
    produto_id bigint NOT NULL,
    valor_custo double precision
);


ALTER TABLE public.estoque OWNER TO technomade;

--
-- Name: estoque_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.estoque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estoque_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grupo_precificacao; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.grupo_precificacao (
    id bigint NOT NULL,
    margem_lucro double precision NOT NULL,
    nome character varying(255) NOT NULL
);


ALTER TABLE public.grupo_precificacao OWNER TO technomade;

--
-- Name: grupo_precificacao_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.grupo_precificacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupo_precificacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itens_carrinho; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.itens_carrinho (
    id bigint NOT NULL,
    quantidade integer NOT NULL,
    reservado_ate timestamp(6) without time zone NOT NULL,
    produto_id bigint NOT NULL,
    cliente_id bigint NOT NULL
);


ALTER TABLE public.itens_carrinho OWNER TO technomade;

--
-- Name: itens_carrinho_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.itens_carrinho ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_carrinho_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itens_compra; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.itens_compra (
    id bigint NOT NULL,
    preco_unitario double precision NOT NULL,
    quantidade integer NOT NULL,
    compra_id bigint NOT NULL,
    produto_id bigint NOT NULL
);


ALTER TABLE public.itens_compra OWNER TO technomade;

--
-- Name: itens_compra_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.itens_compra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_compra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itens_troca; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.itens_troca (
    id bigint NOT NULL,
    quantidade integer NOT NULL,
    produto_id bigint NOT NULL,
    troca_id bigint NOT NULL
);


ALTER TABLE public.itens_troca OWNER TO technomade;

--
-- Name: itens_troca_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.itens_troca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_troca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimentacoes_estoque; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.movimentacoes_estoque (
    id bigint NOT NULL,
    data_hora timestamp(6) without time zone,
    fornecedor character varying(255),
    quantidade integer NOT NULL,
    tipo character varying(255) NOT NULL,
    valor_custo double precision NOT NULL,
    produto_id bigint NOT NULL,
    CONSTRAINT movimentacoes_estoque_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ENTRADA'::character varying, 'SAIDA'::character varying])::text[])))
);


ALTER TABLE public.movimentacoes_estoque OWNER TO technomade;

--
-- Name: movimentacoes_estoque_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.movimentacoes_estoque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimentacoes_estoque_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificacoes; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.notificacoes (
    id bigint NOT NULL,
    data_hora timestamp(6) without time zone NOT NULL,
    lida boolean NOT NULL,
    mensagem character varying(500) NOT NULL,
    referencia_id bigint,
    referencia_tipo character varying(50),
    tipo character varying(255) NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT notificacoes_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['TROCA_AUTORIZADA'::character varying, 'CARRINHO_EXPIRANDO'::character varying, 'ESTOQUE_ALTERADO'::character varying, 'COMPRA_APROVADA'::character varying, 'COMPRA_REPROVADA'::character varying, 'COMPRA_EM_TRANSITO'::character varying, 'COMPRA_ENTREGUE'::character varying, 'TROCA_RECEBIDA'::character varying, 'CUPOM_GERADO'::character varying, 'GERAL'::character varying])::text[])))
);


ALTER TABLE public.notificacoes OWNER TO technomade;

--
-- Name: notificacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.notificacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pagamentos; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.pagamentos (
    id bigint NOT NULL,
    data_pagamento timestamp(6) without time zone,
    forma_pagamento character varying(255) NOT NULL,
    valor double precision NOT NULL,
    cartao_credito_id bigint,
    compra_id bigint NOT NULL,
    cupom_id bigint,
    CONSTRAINT pagamentos_forma_pagamento_check CHECK (((forma_pagamento)::text = ANY ((ARRAY['CARTAO_CREDITO'::character varying, 'CUPOM_PROMOCIONAL'::character varying, 'CUPOM_TROCA'::character varying])::text[])))
);


ALTER TABLE public.pagamentos OWNER TO technomade;

--
-- Name: pagamentos_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.pagamentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagamentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedidos_troca; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.pedidos_troca (
    id bigint NOT NULL,
    data_conclusao timestamp(6) without time zone,
    data_solicitacao timestamp(6) without time zone NOT NULL,
    status_troca character varying(255) NOT NULL,
    compra_id bigint NOT NULL,
    motivo character varying(255),
    CONSTRAINT pedidos_troca_status_troca_check CHECK (((status_troca)::text = ANY ((ARRAY['EM_TROCA'::character varying, 'TROCA_AUTORIZADA'::character varying, 'TROCA_RECUSADA'::character varying, 'TROCADA'::character varying])::text[])))
);


ALTER TABLE public.pedidos_troca OWNER TO technomade;

--
-- Name: pedidos_troca_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.pedidos_troca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_troca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produto_categoria; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.produto_categoria (
    produto_id bigint NOT NULL,
    categoria_id bigint NOT NULL
);


ALTER TABLE public.produto_categoria OWNER TO technomade;

--
-- Name: produtos; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.produtos (
    id bigint NOT NULL,
    altura double precision NOT NULL,
    ativo boolean NOT NULL,
    codigo_barras character varying(255) NOT NULL,
    descricao character varying(255) NOT NULL,
    imagem_url character varying(255) NOT NULL,
    largura double precision NOT NULL,
    marca character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    peso double precision NOT NULL,
    profundidade double precision NOT NULL,
    valor_custo double precision NOT NULL,
    valor_venda double precision NOT NULL,
    grupo_precificacao_id bigint,
    data_ativacao timestamp(6) without time zone,
    data_inativacao timestamp(6) without time zone,
    justificativa_ativacao character varying(255),
    justificativa_inativacao character varying(255),
    motivo_ativacao character varying(255),
    motivo_inativacao character varying(255),
    ultima_acao character varying(255),
    ultima_data timestamp(6) without time zone,
    ultima_justificativa character varying(255),
    ultimo_motivo character varying(255),
    CONSTRAINT produtos_motivo_ativacao_check CHECK (((motivo_ativacao)::text = ANY ((ARRAY['LANCAMENTO'::character varying, 'RETORNO_MERCADO'::character varying, 'CORRECAO_CADASTRO'::character varying, 'OUTRO'::character varying])::text[]))),
    CONSTRAINT produtos_motivo_inativacao_check CHECK (((motivo_inativacao)::text = ANY ((ARRAY['FORA_DE_MERCADO'::character varying, 'SEM_ESTOQUE'::character varying, 'DESCONTINUADO'::character varying, 'OUTRO'::character varying])::text[]))),
    CONSTRAINT produtos_ultima_acao_check CHECK (((ultima_acao)::text = ANY ((ARRAY['ATIVACAO'::character varying, 'INATIVACAO'::character varying])::text[])))
);


ALTER TABLE public.produtos OWNER TO technomade;

--
-- Name: produtos_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.produtos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produtos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: technomade
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    senha character varying(255) NOT NULL,
    cpf character varying(255),
    endereco character varying(255),
    telefone character varying(255),
    data_nascimento date,
    genero character varying(255),
    CONSTRAINT usuarios_genero_check CHECK (((genero)::text = ANY ((ARRAY['MASCULINO'::character varying, 'FEMININO'::character varying])::text[]))),
    CONSTRAINT usuarios_role_check CHECK (((role)::text = ANY ((ARRAY['CLIENTE'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.usuarios OWNER TO technomade;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: technomade
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auditoria_logs auditoria_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.auditoria_logs
    ADD CONSTRAINT auditoria_logs_pkey PRIMARY KEY (id);


--
-- Name: cartoes_credito cartoes_credito_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.cartoes_credito
    ADD CONSTRAINT cartoes_credito_pkey PRIMARY KEY (id);


--
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- Name: compras compras_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.compras
    ADD CONSTRAINT compras_pkey PRIMARY KEY (id);


--
-- Name: cupons cupons_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.cupons
    ADD CONSTRAINT cupons_pkey PRIMARY KEY (id);


--
-- Name: enderecos_entrega enderecos_entrega_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.enderecos_entrega
    ADD CONSTRAINT enderecos_entrega_pkey PRIMARY KEY (id);


--
-- Name: estoque estoque_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.estoque
    ADD CONSTRAINT estoque_pkey PRIMARY KEY (id);


--
-- Name: grupo_precificacao grupo_precificacao_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.grupo_precificacao
    ADD CONSTRAINT grupo_precificacao_pkey PRIMARY KEY (id);


--
-- Name: itens_carrinho itens_carrinho_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_carrinho
    ADD CONSTRAINT itens_carrinho_pkey PRIMARY KEY (id);


--
-- Name: itens_compra itens_compra_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_compra
    ADD CONSTRAINT itens_compra_pkey PRIMARY KEY (id);


--
-- Name: itens_troca itens_troca_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_troca
    ADD CONSTRAINT itens_troca_pkey PRIMARY KEY (id);


--
-- Name: movimentacoes_estoque movimentacoes_estoque_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT movimentacoes_estoque_pkey PRIMARY KEY (id);


--
-- Name: notificacoes notificacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT notificacoes_pkey PRIMARY KEY (id);


--
-- Name: pagamentos pagamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.pagamentos
    ADD CONSTRAINT pagamentos_pkey PRIMARY KEY (id);


--
-- Name: pedidos_troca pedidos_troca_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.pedidos_troca
    ADD CONSTRAINT pedidos_troca_pkey PRIMARY KEY (id);


--
-- Name: produto_categoria produto_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.produto_categoria
    ADD CONSTRAINT produto_categoria_pkey PRIMARY KEY (produto_id, categoria_id);


--
-- Name: produtos produtos_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT produtos_pkey PRIMARY KEY (id);


--
-- Name: usuarios uk2et2smpfrtsohr7w9fe1v8a5e; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uk2et2smpfrtsohr7w9fe1v8a5e UNIQUE (cpf);


--
-- Name: itens_carrinho uk4ct1ag2giyqcq071abg2tf7f; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_carrinho
    ADD CONSTRAINT uk4ct1ag2giyqcq071abg2tf7f UNIQUE (cliente_id, produto_id);


--
-- Name: clientes uk7wflw78ibh162cmq12ii6ffly; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT uk7wflw78ibh162cmq12ii6ffly UNIQUE (cpf);


--
-- Name: clientes uk96x1n5ut15ns1xhkm87y7qhnd; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT uk96x1n5ut15ns1xhkm87y7qhnd UNIQUE (usuario_id);


--
-- Name: itens_carrinho uk_itens_carrinho_cliente_produto; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_carrinho
    ADD CONSTRAINT uk_itens_carrinho_cliente_produto UNIQUE (cliente_id, produto_id);


--
-- Name: produtos ukdaeo2r0ngi2v5ejdny1pcus89; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT ukdaeo2r0ngi2v5ejdny1pcus89 UNIQUE (codigo_barras);


--
-- Name: cupons ukfwxbn8wj3xijqpw9x0hevuba6; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.cupons
    ADD CONSTRAINT ukfwxbn8wj3xijqpw9x0hevuba6 UNIQUE (codigo);


--
-- Name: usuarios ukkfsp0s1tflm1cwlj8idhqsad0; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: notificacoes fk3jcnk0ggmxklk5sjxm2plk5ml; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT fk3jcnk0ggmxklk5sjxm2plk5ml FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: pagamentos fk46j2r5icyba3vt1o3e8xud81b; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.pagamentos
    ADD CONSTRAINT fk46j2r5icyba3vt1o3e8xud81b FOREIGN KEY (cupom_id) REFERENCES public.cupons(id);


--
-- Name: cartoes_credito fk85y764m27c5pbilbjjr4h8n4f; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.cartoes_credito
    ADD CONSTRAINT fk85y764m27c5pbilbjjr4h8n4f FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: compras fk89ge5wb6wxi952n1buo3o0etg; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.compras
    ADD CONSTRAINT fk89ge5wb6wxi952n1buo3o0etg FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: pagamentos fk8yyflj8j51x78tjop9njojb5o; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.pagamentos
    ADD CONSTRAINT fk8yyflj8j51x78tjop9njojb5o FOREIGN KEY (compra_id) REFERENCES public.compras(id);


--
-- Name: itens_troca fk9ifijvf3thc92qo4qb3pn3ia6; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_troca
    ADD CONSTRAINT fk9ifijvf3thc92qo4qb3pn3ia6 FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- Name: cartoes_credito fk_cartoes_credito_cliente; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.cartoes_credito
    ADD CONSTRAINT fk_cartoes_credito_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: compras fk_compras_cliente; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.compras
    ADD CONSTRAINT fk_compras_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: cupons fk_cupons_cliente; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.cupons
    ADD CONSTRAINT fk_cupons_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: enderecos_entrega fk_enderecos_entrega_cliente; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.enderecos_entrega
    ADD CONSTRAINT fk_enderecos_entrega_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: itens_carrinho fk_itens_carrinho_cliente; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_carrinho
    ADD CONSTRAINT fk_itens_carrinho_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: itens_carrinho fkas29vkil8nc305nkhao3d9h0b; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_carrinho
    ADD CONSTRAINT fkas29vkil8nc305nkhao3d9h0b FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- Name: produtos fkb6xo83255e5shso2v9j85hjx8; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT fkb6xo83255e5shso2v9j85hjx8 FOREIGN KEY (grupo_precificacao_id) REFERENCES public.grupo_precificacao(id);


--
-- Name: produto_categoria fkd699xsx1mp9nqpa0jv40xj0i2; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.produto_categoria
    ADD CONSTRAINT fkd699xsx1mp9nqpa0jv40xj0i2 FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- Name: compras fkdl9hiv10a1rse1ufs4hnqkfx1; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.compras
    ADD CONSTRAINT fkdl9hiv10a1rse1ufs4hnqkfx1 FOREIGN KEY (endereco_entrega_id) REFERENCES public.enderecos_entrega(id);


--
-- Name: pagamentos fke0gp8ouaw5rp12k562wbii7kc; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.pagamentos
    ADD CONSTRAINT fke0gp8ouaw5rp12k562wbii7kc FOREIGN KEY (cartao_credito_id) REFERENCES public.cartoes_credito(id);


--
-- Name: pedidos_troca fkey2hnb8ys1ipsd3qspwq7yviw; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.pedidos_troca
    ADD CONSTRAINT fkey2hnb8ys1ipsd3qspwq7yviw FOREIGN KEY (compra_id) REFERENCES public.compras(id);


--
-- Name: itens_compra fkfvaabb03he8nwqm7w3c3350xy; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_compra
    ADD CONSTRAINT fkfvaabb03he8nwqm7w3c3350xy FOREIGN KEY (compra_id) REFERENCES public.compras(id);


--
-- Name: enderecos_entrega fkhb1ctlp0dt0qct7r8wvyyej2t; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.enderecos_entrega
    ADD CONSTRAINT fkhb1ctlp0dt0qct7r8wvyyej2t FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: itens_compra fkjspbv1ss3c67f7togq9fvugwg; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_compra
    ADD CONSTRAINT fkjspbv1ss3c67f7togq9fvugwg FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- Name: clientes fkk6iwsq3kts1bblivkjy6epajx; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT fkk6iwsq3kts1bblivkjy6epajx FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: cupons fkm04vm57awb4rtat61hdwy46hk; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.cupons
    ADD CONSTRAINT fkm04vm57awb4rtat61hdwy46hk FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: movimentacoes_estoque fkmdn52qx0fmc71ejys5cmetpjc; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT fkmdn52qx0fmc71ejys5cmetpjc FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- Name: estoque fkmonotpf9w7pfuomk89nqxgeq1; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.estoque
    ADD CONSTRAINT fkmonotpf9w7pfuomk89nqxgeq1 FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- Name: itens_carrinho fknuqnu7kw2dor90dv2ft98m9yr; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_carrinho
    ADD CONSTRAINT fknuqnu7kw2dor90dv2ft98m9yr FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: produto_categoria fkq73dxu7fw55sqpj0fgvnvh31b; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.produto_categoria
    ADD CONSTRAINT fkq73dxu7fw55sqpj0fgvnvh31b FOREIGN KEY (categoria_id) REFERENCES public.categorias(id);


--
-- Name: itens_troca fkraguqsw9ivcsut7wm8s91a9q; Type: FK CONSTRAINT; Schema: public; Owner: technomade
--

ALTER TABLE ONLY public.itens_troca
    ADD CONSTRAINT fkraguqsw9ivcsut7wm8s91a9q FOREIGN KEY (troca_id) REFERENCES public.pedidos_troca(id);


--
-- PostgreSQL database dump complete
--

\unrestrict xEJwEGIQdkILJJ8gcuXaVfVZ2n9ToS57vYXqp9vdMEy5hGsHKbtnX0FUeOuAV3b

